### ISSUE TITLE
J!5.1 JEM4.2.1dev php 8.2.16 Backend>venue edit>save -->error

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1713] opened 2024-04-17 07:42 UTC
0 Call to a member function format() on bool 

# | Function | Location
-- | -- | --
1 | () | JROOT/libraries/src/Form/Field/CalendarField.php:400
2 | Joomla\CMS\Form\Field\CalendarField->filter() | JROOT/libraries/src/Form/Form.php:1047
3 | Joomla\CMS\Form\Form->filter() | JROOT/libraries/src/Form/Form.php:991
4 | Joomla\CMS\Form\Form->process() | JROOT/libraries/src/MVC/Model/FormModel.php:219
5 | Joomla\CMS\MVC\Model\FormModel->validate() | JROOT/libraries/src/MVC/Controller/FormController.php:636
6 | Joomla\CMS\MVC\Controller\FormController->save() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
7 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/administrator/components/com_jem/jem.php:54
8 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
9 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
10 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
11 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:150
12 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:195
13 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
14 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:58
15 | require_once() | JROOT/administrator/index.php:32

**Comment by jojo12** [comment] 2024-04-17 14:36
Problem is only in backend

**Comment by mckillo** [comment] 2024-04-17 14:43
In <field name="created" type="calendar"  and 	<field name="modified" type="calendar"
into administrator\components\com_jem\models\forms\venue.xml, add these lines:
```
filterformat="Y-m-d H:i:s"
showtime="true"

```
like this:
![image](https://github.com/jemproject/JEM-Project/assets/2765316/12376696-18d5-4511-9b75-0a9d0980806f)

Tell me, if it works.

**Comment by jobrusche** [comment] 2024-04-17 15:10
Well on a site of mine, it did not fix it

**Comment by jojo12** [comment] 2024-04-17 15:59
For me, this is fixing the issue!

**Comment by mckillo** [comment] 2024-04-17 16:21
Tell me any data of site. 
Do you apply the last commit of JEM 4.2.1dev? (refresh)

**Comment by mckillo** [comment] 2024-04-17 16:43
Ups, but does it solve the problem or not? I don't have clear your situations (yes, no...)
I had simulated the error, and this solves it.
I'm on JL 5.1, PHP 8.2 and JEM 4.2.1 dev

**Comment by jobrusche** [comment] 2024-04-17 16:46
I do not have JEM 4.2.1 installed, I just edited venue.xml

**Comment by jojo12** [comment] 2024-04-17 17:48
php 8.2.16 J!5.1 JEM 4.2.1dev and your proposal
sorry I was on the dinner
it's not yet fixed

**Comment by mckillo** [comment] 2024-04-17 17:51
Send a capture with php error, is the same error? In the venus view when save.

**Comment by jojo12** [comment] 2024-04-17 17:56
@jobrusche: which language are you using?

**Comment by mckillo** [comment] 2024-04-17 18:08
This night, I will try to simulate the erro in other languages....could be.

**Comment by jojo12** [comment] 2024-04-17 18:10
now stack is:

1 | () | JROOT/libraries/src/Form/Field/CalendarField.php:400
-- | -- | --
2 | Joomla\CMS\Form\Field\CalendarField->filter() | JROOT/libraries/src/Form/Form.php:1047
3 | Joomla\CMS\Form\Form->filter() | JROOT/libraries/src/Form/Form.php:991
4 | Joomla\CMS\Form\Form->process() | JROOT/libraries/src/MVC/Model/FormModel.php:219
5 | Joomla\CMS\MVC\Model\FormModel->validate() | JROOT/libraries/src/MVC/Controller/FormController.php:636
6 | Joomla\CMS\MVC\Controller\FormController->save() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
7 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/administrator/components/com_jem/jem.php:54
8 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
9 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
10 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
11 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:150
12 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:195
13 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
14 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:58
15 | require_once() | JROOT/administrator/index.php:32

**Comment by jobrusche** [comment] 2024-04-17 19:52
I'm using nl-BE (Flemish)
I switched to en-GB(admin) and now the new location can be saved without error.

**Comment by mckillo** [comment] 2024-04-17 20:05
Yes, with JL5.1 in spanish, I have the error. Let's me debug it.

**Comment by mckillo** [comment] 2024-04-17 22:34
I try to explain the issue:
When create or edit a venue item, on the right side there is a created field. This field is created datetime of venue item.
This datetime is created in english format.
In the venue.xml have the translateformat attribute for this calendar field. When the translateformat is true, the created field in the view is shown in the language of Joomla backend, only show because the value of this field is english format.

The issue is when you want to save the venue because Joomla compares the value (EN) with your datetime format of language of backend, and it isn't compatible and have the error result.

This issue is opened in Joomla:
https://issues.joomla.org/tracker/joomla-cms/41224
https://github.com/joomla/joomla-cms/issues/41444

For the moment, the best solution is to change "translateformat=false", so, the created field will be shown in english format, and you can save the data without error.
![image](https://github.com/jemproject/JEM-Project/assets/2765316/ba23f28c-23e0-4519-83ee-600204032054)

Tell me if it works in other languages, for me with the backend in spanish, it works too.

**Comment by mckillo** [comment] 2024-04-17 22:37
When you confirm, I will upload a commit with this workaround --> translateformat ="false" in venue.xml, so, it will be included in the next version JEM 4.2.1

**Comment by jojo12** [comment] 2024-04-18 04:49
Before starting to test, I wonder:
The dates for created and modified are e.g. in events too, BUT there is no problem. The same, when I edit venue in frontend: no problem! (No problem too in categories, groups...)

**Comment by jojo12** [comment] 2024-04-18 05:37
I made the indicated changes and tested in backend and frontend in german and english (always with clean cache) it works as you describe (without a german dateformat)

**Comment by mckillo** [comment] 2024-04-18 06:35
In frontend, JEM doesn't show the created datetime and this field is created when the event and venues are saved. The category and group don't have XML form file. 
I don't understand why the JEM backend has to show the created datetime on the right side for a new item (venues), As a solution, it could be showed in text mode (these fields are read-only).

**Comment by mckillo** [comment] 2024-04-21 08:40
@joo12 can it be closed or no this issue? I think that it's fixed.

**Closed** 2024-04-21 09:13 UTC
Labels: bug, fixed, J5.1
