### ISSUE TITLE
Book several Tickets at once per user

### ISSUE THREAD

**Issue by mckillo** [jemproject/JEM-Project#1573] opened 2023-05-26 07:48 UTC
Proposal to dev this feature, see https://www.joomlaeventmanager.net/forum/general-topics,-help-and-tutorials/12323-book-several-tickets-at-once#30263

Now, if an event has active the registration, each user can take 1 place for event. If we add a new field of registration setting, with the maximum number of seats per user and in the event, the user change choose the number from 1 to Max/user, we have it, it's easy and simple.

What are your opinion?

**Comment by jojo12** [comment] 2023-05-26 08:37
Would really be good and helpful! I agree, please😉

**Comment by mckillo** [comment] 2023-05-26 09:01
![JEM4-Proposal_define_booked_number_tickets_per_user](https://github.com/jemproject/JEM-Project/assets/2765316/d847026b-bc12-4442-909c-880178f93ef0)

In the backend, only need 2 new field for define the min and max places that one user can be booked.

**Comment by mckillo** [comment] 2023-05-26 09:02
I'll get to it

**Comment by mckillo** [comment] 2023-05-26 10:52
Reserved places? I guess that these nº places are by invitation or reserved (not available for users), right? bt now it's disabled, Shall we activate it?

**Comment by jojo12** [comment] 2023-05-26 11:11
Yes

**Comment by mckillo** [comment] 2023-05-28 12:46
![JEM4-Proposal_define_booked_number_tickets_per_user- options_user-frontend (default and responsive_style)](https://github.com/jemproject/JEM-Project/assets/2765316/d1377c60-208d-4f42-a4fe-bd09d446c06d)

The new design is understood.

**Comment by jojo12** [comment] 2023-05-28 15:55
I don't understand. The legacy style (you say: standard) is broken.
and the responsive is not like you describe. (see image)
![grafik](https://github.com/jemproject/JEM-Project/assets/2960236/569ef0cc-77b3-4916-8fa7-c493062dd613)

**Comment by mckillo** [comment] 2023-05-28 16:21
Sorry, it was a capture, I don't upload the last code. 
Give me a hours to return home and upload new commit.

**Comment by jojo12** [comment] 2023-05-28 16:22
don't hurry ! 👍

**Comment by mckillo** [comment] 2023-05-28 18:05
@jojo12 Here you are, I have already uploaded (see commit above). Test it and tell me if it's fine.

**Comment by mckillo** [comment] 2023-05-28 18:35
This next week I'll have to change the backend views affected and change the mail template. This is the second part of this new feature.

**Comment by jojo12** [comment] 2023-05-28 20:07
tomorrow🥱

**Comment by mckillo** [comment] 2023-05-29 21:44
![JEM4-Proposal_define_booked_number_tickets_per_user- options_user-frontend (user cancesl booked places)](https://github.com/jemproject/JEM-Project/assets/2765316/d2c6669d-763f-4b99-ab48-43e4ab411f69)

**Comment by jojo12** [comment] 2023-05-30 05:22
I agree

**Comment by mckillo** [comment] 2023-05-30 07:41
Fix fo 'Reserved Places'. Change in \components\com_jem\views\event\tmpl\responsive\default_attendees.php:
the line 38:
`<a href="<?php echo $linkreg; ?>" title="<?php echo Text::_('COM_JEM_MYEVENT_MANAGEATTENDEES'); ?>"><?php echo $this->item->booked; ?> <i class="icon-out-2" aria-hidden="true"></i></a>`
for this one:
`<a href="<?php echo $linkreg; ?>" title="<?php echo Text::_('COM_JEM_MYEVENT_MANAGEATTENDEES'); ?>"><?php echo $reservedplaces; ?> <i class="icon-out-2" aria-hidden="true"></i></a>`

**Comment by mckillo** [comment] 2023-05-30 07:55
![JEM4-Proposal_define_booked_number_tickets_per_user- options_user-frontend (news version text to book)](https://github.com/jemproject/JEM-Project/assets/2765316/48e085ab-bd29-4b4b-a331-9e0dfeed5337)

Tell me if this version of text is better-

**Comment by mckillo** [comment] 2023-05-30 08:10
The admin can change the string in \components\com_jem\language\en-GB\en-GB.com_jem.ini

![JEM4-Proposal_define_booked_number_tickets_per_user- options_user-frontend (language strings)](https://github.com/jemproject/JEM-Project/assets/2765316/11a24a5a-7216-4c3f-a2ac-de4a14c33811)

**Comment by mckillo** [comment] 2023-05-30 08:56
![JEM4-Proposal_define_booked_number_tickets_per_user- options_user-frontend (disable option to bokke more is there are 0 available)](https://github.com/jemproject/JEM-Project/assets/2765316/12ddeb6a-6f5e-4f74-9f01-328574c52814)

In last commit, a small details, if there aren't places available, then the option is disable to add more.

**Comment by mckillo** [comment] 2023-05-30 09:03
![JEM4-Proposal_define_booked_number_tickets_per_user- options_user-frontend (additional places when user have any reserved places)](https://github.com/jemproject/JEM-Project/assets/2765316/0b03ca79-5334-4b1c-af59-db75c36cd1de)

**Comment by mckillo** [comment] 2023-05-30 09:09
![JEM4-Proposal_define_booked_number_tickets_per_user- options_user-frontend (edit places for user)](https://github.com/jemproject/JEM-Project/assets/2765316/fa881470-c842-4ce9-9cbf-2ef0f7ecdff1)

Now, with this feature, the admin can change/add the status of users for the event. It works, I can invite of user with content of email. The admin can add more or cancel places of the users too.

**Comment by jojo12** [comment] 2023-05-30 10:24
BUG: My administrator was first "not attending" and wants to change to "attending", but he can't even if it is written. This in event view

**Comment by mckillo** [comment] 2023-05-30 10:40
I don't see the error when trying to operate places with the users. Give me some more details to try to reproduce it.

**Comment by mckillo** [comment] 2023-05-30 10:43
About ZIP, I don't know. I don't know, in principle there is no field with the old notation (datetime format).
Send it private with the ZIP.

**Comment by jojo12** [comment] 2023-05-30 10:45
I don't understand: Shall I send or will you send it with the ZIP?

**Comment by mckillo** [comment] 2023-05-30 10:46
Your ZIP, send me and check it.

**Comment by jojo12** [comment] 2023-05-30 11:13
i get errors:
tmpl/default_regform.php on line 62 Warning: Undefined array key ""  and Warning: Attempt to read property "places" on null 
same in line 68
same in responsive line 63 and 69

**Comment by mckillo** [comment] 2023-05-30 13:50
I have installed jem_com.zip and it's OK.
And the error (without user logged on) is solved in the following commit (see below).

**Comment by jojo12** [comment] 2023-05-30 16:00
sorry, backend reg.users:
![grafik](https://github.com/jemproject/JEM-Project/assets/2960236/489f7bfa-29e7-4651-acbb-066afc8937c9)

**Comment by mckillo** [comment] 2023-05-30 20:48
@jojo13 myevent view fixed. I don't review this view with change ( I don't use it). See the update commit above.

Respect the function of status icon, to change status... I have to review the code, but I can tell you that I haven't change anything about this icon, because the code of status are the same. I suppose that before it doesn't work. Review it tomorrow.

**Comment by mckillo** [comment] 2023-05-31 09:04
@jojo See commit above. Fixed the action of status icon (attending <-> waiting list).

**Comment by jojo12** [comment] 2023-05-31 09:36
Thanks.
I've just seen: Before max.places= 0 were for unlimited places. Now it says, they are no more places.
It needs a possibility to announce the attending, even when the places are not limited!

**Comment by mckillo** [comment] 2023-05-31 09:39
https://user-images.githubusercontent.com/2765316/241905552-12ddeb6a-6f5e-4f74-9f01-328574c52814.jpg

Yes, in previous image, the attending can see if there is places or not.

**Comment by mckillo** [comment] 2023-05-31 09:50
I understand it, you are the best tester of JEM, and the time is limit and I have the same issue, we don't have time. A lot time to dev/test this feature and I have resolved of issues/bug about it. If you think that it isn't ready ... next release, but I have my opinion about unify code of branchs by dev forum.

**Comment by mckillo** [comment] 2023-05-31 10:00
I'm going to test max.places=0 and change to active the option for unlimited places.

**Comment by jojo12** [comment] 2023-05-31 10:02
I understand and we can unify the branches. But somewhere we have to cut. It's a pity, it's a nice playground and there are so good ideas!
RC should work without problems in Joomla!4. 
Joomla!5 and 6 is later!

**Comment by jojo12** [comment] 2023-05-31 10:10
The settings for event reservation in legacy and default style are different. in default is an old form.

**Comment by mckillo** [comment] 2023-05-31 14:06
![JEM4-Proposal_define_booked_number_tickets_per_user- options_user-frontend (change stadistic style)](https://github.com/jemproject/JEM-Project/assets/2765316/fc080a34-2b48-4263-ab08-88958fb41c48)

I have changed the style, now I suppose that it's more clear.
Now, the legacy and default are the same style (I don't have translate the change to other style).
The Manage attendees view from frontend is updated too (add places).
And the end, now hte admin can max.places=0 (by default) to create event with unlimited places (recommendation set the max.booked per user).

See below the new commit with all these changes.

**Comment by mckillo** [comment] 2023-05-31 18:35
Fixed

**Comment by jojo12** [comment] 2023-06-01 05:47
![grafik](https://github.com/jemproject/JEM-Project/assets/2960236/2fdebf90-cd06-45e6-925a-90b72e549212)

**Comment by jojo12** [comment] 2023-06-01 05:52
![grafik](https://github.com/jemproject/JEM-Project/assets/2960236/57d42cf4-b47c-4c3b-9f65-7adb207fe44a)

**Comment by jojo12** [comment] 2023-06-01 06:03
1) In attendees Manager I add a user on waitinglist.  it's right: he has 0 reserved place.
Then I put him (with click on the hourglass) on the list of attendees. He continues to need 0 place. This is wrong. He needs at least 1 place!
2) in attendees Manager I add a user on attendinglist. But he uses 0 place. This is wrong. He can't participate without place!
3) in attendees Manager I add a user as invited. Is it right, that he has no reserved place, before he is accepting his invitation?

**Comment by jojo12** [comment] 2023-06-01 06:08
1) from attendees Manager the print and the export don't have the number of places!
2) and the date should be abreviated (the long date isn't needed)

**Comment by Kralyk** [comment] 2023-06-01 06:10
Hello everyone, since you are already creating this tweak, I have a suggestion for one more tweak, it probably wouldn't take much work to program it.

It would be great if this list of attendees also displayed the text of their registration notes. With an option in the administration to turn this off or on.

**Comment by jojo12** [comment] 2023-06-01 06:15
![grafik](https://github.com/jemproject/JEM-Project/assets/2960236/f24d0071-a10c-468e-a883-d513c326c2ce)

**Comment by jojo12** [comment] 2023-06-01 06:26
![grafik](https://github.com/jemproject/JEM-Project/assets/2960236/301cc18b-32e0-4d1b-8dce-cec7055ce6cc)

**Comment by jojo12** [comment] 2023-06-01 06:30
@Kralyk you wrote:

> It would be great if this list of attendees also displayed the text of their registration notes. With an option in the administration to turn this off or on.
what do you mean with "registration notes"?

**Comment by Kralyk** [comment] 2023-06-01 06:38
> what do you mean with "registration notes"?

When registering for an event, a participant can write a optional comment on their registration (e.g. another participant's name, a note that they will come back later, etc.).

**Comment by jojo12** [comment] 2023-06-01 06:40
when max. places are unlimited and
if there are "reserved places=0", I have no link to Attendee Manager

**Comment by jojo12** [comment] 2023-06-01 06:43
@Kralyk 

> When registering for an event, a participant can write a optional comment on their registration (e.g. another participant's name, a note that they will come back later, etc.).

This is there, you can try!

**Comment by Kralyk** [comment] 2023-06-01 06:51
> 
> This is there, you can try! only the number of places are missing! !

 I think this listing is only displayed to the "founder" of the event or the admin. But maybe I'm wrong.

I meant for it to be displayed directly in the event for all event attendees (even unregistered ones) right next to the names of the already registered attendees.

**Comment by jojo12** [comment] 2023-06-01 07:09
What are your JEM settings<Event page<Registration?

**Comment by jojo12** [comment] 2023-06-01 07:21
![grafik](https://github.com/jemproject/JEM-Project/assets/2960236/3aff6331-802b-42f5-99dc-2d5de282db54)

**Comment by mckillo** [comment] 2023-06-01 07:45
Yes, I agree both. 
In the Registered Users, I change from +1 reserved place to +1 booked place, ok?

**Comment by mckillo** [comment] 2023-06-01 07:46
I have the location improvements
![JEM4-Proposal_define_booked_number_tickets_per_user- options_user-frontend (location improvements)](https://github.com/jemproject/JEM-Project/assets/2765316/20fea5ad-6c57-49a6-8ece-0bf929b7b19c)
Do you agree?

**Comment by mckillo** [comment] 2023-06-01 07:56
Now, I'm going to copy these change in the legacy style and upload a new comit.

**Comment by mckillo** [comment] 2023-06-01 08:36
![JEM4-Proposal_define_booked_number_tickets_per_user- options_user-frontend (change status of registration users)](https://github.com/jemproject/JEM-Project/assets/2765316/7cd6548b-0ec2-4733-b605-2e37e9cefcf4)

This isn't changed in JEM.

**Comment by jojo12** [comment] 2023-06-01 09:58
looks good, I'll wait :-)

**Comment by mckillo** [comment] 2023-06-01 15:16
![JEM4-Proposal_define_booked_number_tickets_per_user- options_user-frontend (bold line of the user)](https://github.com/jemproject/JEM-Project/assets/2765316/ef741dad-e435-460a-9581-39a60311b41d)

And the add user from Manage Attendees works to add number of places. 
I'm sorry for the delay, the day has been complicated. Give me a minutes and upload commit.

**Comment by jojo12** [comment] 2023-06-01 15:21
Yes, real live goes first!

**Comment by mckillo** [comment] 2023-06-01 15:37
@jojo12 Here you are.... a lot of changes. Look fine... thanks for your testing.

**Comment by jojo12** [comment] 2023-06-01 17:16
![grafik](https://github.com/jemproject/JEM-Project/assets/2960236/097b0dbb-8459-44d7-bd58-bcb2af1b3578)

**Comment by mckillo** [comment] 2023-06-01 17:25
About clic before, this isn't change. When the user is new (don't have any registratioin), any check is checked, the user has to select  if go or not. You need clic first in the check (set). It's depend of bootstrap style or the css template setting.

**Comment by jojo12** [comment] 2023-06-01 17:27
![grafik](https://github.com/jemproject/JEM-Project/assets/2960236/4c0dd56e-0f49-486a-b075-9e67d7728abc)

**Comment by jojo12** [comment] 2023-06-01 17:31
What does mean: "Minimum booked per user"?

**Comment by mckillo** [comment] 2023-06-01 17:33
COM_JEM_LAST_COMMENT is solved in new commit 041c2e14f891465ef91db2c650c736438467a455

**Comment by jojo12** [comment] 2023-06-01 17:34
Minimum booked per user
Maximum booked per user
Reserved places 
should be in the frontend settings of an event too! (I think)
--> I want to give the possibility to a other user to create an event with these possibilities

**Comment by mckillo** [comment] 2023-06-01 17:35
Minimum booked per user is the minimum number of places to booked per user. For example, you can create a meeting (event) and the booked places start from 2 (by deafult 1).

**Comment by mckillo** [comment] 2023-06-01 17:36
These values are stteing in each event.

**Comment by jojo12** [comment] 2023-06-01 17:53
Until now I tested only frontend and backend from the component. I will then go to the mailer plugin!

BUT you're great, it was hard work (more than you thought first - yes?)
I think it is nearby ready to merge.

**Comment by mckillo** [comment] 2023-06-01 17:57
I thought it was less but it has many ramifications in the code, at the end, it's a important change of the structure.
I'm sure that some details to debug or refine, but it works.
Thanks.  email_acl is easy to check/test.

**Comment by mckillo** [comment] 2023-06-01 17:59
When you tell me, I merge it.

**Comment by jojo12** [comment] 2023-06-02 05:14
Good morning! When the event frontend settings in legacy and default are the same, the book tickets can be merged!
 It i a enhancement when plg_jem_mailer can send the number of booked places. Not urgent, but would be good.

**Comment by jojo12** [comment] 2023-06-02 06:49
is this right:
when I have Minimum=0 per user and Maximum 0 per user, I can book unlimited places, even more than there are places!
then it is only written e.g. disponible places = -20 (minus)

when I  have Minimum=0 per user, I can book zero place to participate! That must be **wrong!**

**Comment by mckillo** [comment] 2023-06-02 07:44
it should be so, but review the code to limit until Max.Places when the user is unlimited reservations.

**Comment by mckillo** [comment] 2023-06-02 07:45
![JEM4-Proposal_define_booked_number_tickets_per_user- options_user-frontend (draft to change registration setting of event)](https://github.com/jemproject/JEM-Project/assets/2765316/c332ac0e-d0dc-46b9-b9ed-eb1e225d959d)

Draft of new change in registration setting of event (frontend).

**Comment by jojo12** [comment] 2023-06-02 08:11
Perhaps it would be good to have max booked per user with default=1.

**Comment by mckillo** [comment] 2023-06-02 14:53
Minimum booked per user, Maximum booked per user and Reserved places were as text and now they are number type. For it, Minimum=0 per user isn't a value option, start (min) 1.

Default values when the admin creates a new event:
![JEM4-Proposal_define_booked_number_tickets_per_user- options_user-frontend (default values for new evenl)](https://github.com/jemproject/JEM-Project/assets/2765316/038a6092-a83d-442f-86fa-bda363b1f237)
Minimum can't be 0 (see next commit)

**Comment by mckillo** [comment] 2023-06-02 15:04
![JEM4-Proposal_define_booked_number_tickets_per_user- options_user-frontend (registration data of event in the frontent)](https://github.com/jemproject/JEM-Project/assets/2765316/2b0061a7-7773-46bb-aac8-43dea280c62e)

This is ther result. Like it?

**Comment by mckillo** [comment] 2023-06-02 15:06
Booked Places and Available Places fields are in readonly (info).
I'm going to see the  limit max.places and places into email....after I'll upload commit with all.

**Comment by jojo12** [comment] 2023-06-02 15:25
Yes, looks good!

**Comment by jojo12** [comment] 2023-06-02 16:48
Thanks, after dance I'll have a look.

**Comment by jojo12** [comment] 2023-06-02 22:07
![grafik](https://github.com/jemproject/JEM-Project/assets/2960236/e91b80d2-3272-4099-850c-d196eea6586e)

**Comment by jojo12** [comment] 2023-06-02 22:09
The rest is ok, after correcting the above, the branch can be merged

**Comment by mckillo** [comment] 2023-06-03 05:57
Fixed. See commit above.

**Comment by jojo12** [comment] 2023-06-03 06:15
strange:
It continues to be possible to participate as ghost which don't need a place:
How to reproduce: 
I have minimum per user =1
You go to the button of numbers (of places) and change down to = 0
the you click to participate.
Result: You are participating with (look into attendees manager) 0 place.

**Comment by jojo12** [comment] 2023-06-03 06:16
But I agree, it's only me who is changing down to 0

**Comment by jojo12** [comment] 2023-06-03 06:36
you can merge

**Comment by mckillo** [comment] 2023-06-03 06:40
Here you are. See now (refresh commit).

**Comment by mckillo** [comment] 2023-06-03 06:43
Done. 0 branch.

**Comment by mckillo** [comment] 2023-06-03 06:52
@jojo12 Long and pretty issue .... hard job for testing and dev. Thank you very much for your help.
If last change is fine (I hope so), you would have the honor to close the this case and let's go to the RC.

**Comment by jojo12** [comment] 2023-06-03 06:55
sorry but the ghost continues:
![grafik](https://github.com/jemproject/JEM-Project/assets/2960236/6be334e0-2806-40ef-8d95-1336f2c44be4)

**Comment by mckillo** [comment] 2023-06-03 06:59
How you get 0 places and status 1? It should -1.
Could it be that data was old? I mean, data of previus test?
Tell me the steps/combination to simulate.

**Comment by mckillo** [comment] 2023-06-03 07:00
What status  does [Admin user] have before to have 0?

**Comment by jojo12** [comment] 2023-06-03 07:10
I am in the attendee manager and see the situation like in the image: Jojo Murer (admin) status yes place=0
I delete user with the button and the post is away. I go back to testevent.the admin is disappeared.
I see: "You are not registered yet. To register for this event, please choose one of the options below and send your decision."
I choose "I will go to the event, I want to book 1 place(s)". But I change 1 to 0 (zero) and click "Register".
It sends me the notification "Thank you for your response. Your decision has been stored."
I see in event details that I am registered. (I see only the name). 
I go to attendees manager and see: Jojo Murer (admin) status yes place=0

**Comment by mckillo** [comment] 2023-06-03 07:24
I don't know why you can change to 0 if the minbookeduser =1 (by default), only if it's 0 you could change it to this value.
See new commit. Fix if the user change the value to 0 (from input or in the code), 0 add places will be detected as registration error.

**Comment by jojo12** [comment] 2023-06-03 07:27
![grafik](https://github.com/jemproject/JEM-Project/assets/2960236/4a9d7e55-08e9-4afe-b938-da1dbac5c7ca)
I don't know why too

**Comment by mckillo** [comment] 2023-06-03 07:45
With this setting and last code, I can change to 0 in the registration form of event.
I can do it by change html code (load last commit)....but in this case too, it detects as registration error.

**Comment by jojo12** [comment] 2023-06-03 07:47
yes , I tried:
now I get after clicking register: ERROR: Registration failed! only when I choosed place=0

GREAT

**Comment by jojo12** [comment] 2023-06-03 09:08
once more something:
in JEM settings>event page>Registration there are two items:
Show Attendee Names to
and
Show all related users
The problem: (I am logged in as tester (registrated)
when Show all related users=yes then Show Attendee Names to=disabled nobody 
and
when Show all related users=yes then Show Attendee Names to=disabled, only admins

gives error: array_merge(): Argument #1 must be of type array, bool given

**Comment by jojo12** [comment] 2023-06-03 09:13
AND new problem:
loggedin tester (registered): is registrated for event with 1 place.
He chooses I will not go and clicks register: ERROR: Registration failed!

**Comment by mckillo** [comment] 2023-06-03 09:51
Respect "Show all related users" is status, if 'NO' only show the attendees with places (it doesn't show invited, waiting, not attendees).
if you want, we can change to "Show all status users"

**Comment by mckillo** [comment] 2023-06-03 09:52
I'm going to try simulate errors ... and debug them

**Comment by jojo12** [comment] 2023-06-03 09:59
Only to say: before last commit it was better ( with possible ghost!)

**Comment by mckillo** [comment] 2023-06-03 17:12
I think that it solved about 0, Show all realted user, ...

I have to add new option into "Show Attendee Names to" ... 

![JEM4-Proposal_define_booked_number_tickets_per_user- options_user-frontend (show palces only user)](https://github.com/jemproject/JEM-Project/assets/2765316/3331cbe3-e4be-44e4-9fcc-29894fe6d236)

Because when you select 'Admin' the user don't see anything about number places registrated by this user.

**Comment by mckillo** [comment] 2023-06-03 17:25
Other thing about places: 
I have a doubt the invited user. I think that in JEM2 oesn't work fine, and JEM2 sent ab email and a little more. 
You know, how do users use the invitations places in the JEM2?

Now, this invitation is create by admin, and this places could be the reserved places for the event. The places invited aren't reserved places. If the user wants to go, must cancel this invitations and book new places (if available places).

**Comment by jojo12** [comment] 2023-06-04 15:57
fixed, can be closed

**Comment by jojo12** [comment] 2023-07-28 12:18
my apologies: it was a good idea, but which came too late. And then we wanted to integrate it in JEM 4. 
But we tested not enough, because we wanted to fulfill the scheduled timem to bring JEM 4 out.
The registering for events doesn't work like before, the new programming brings some errors. And our dev, who brought this, has actually not much time to work on it, a big work in real life profession.
What can we do to fix this?
Best would be to uncommit this branch again (if possible) , bring out JEM 4.0.1 with the old registration system and beneath that to clean the book tickets branch separately!

**Comment by jojo12** [comment] 2023-07-28 12:21
The old system worked as:
 each user was able (when logged in) to say yes or no to participate to an event and to give an optional comment.

**Comment by mckillo** [comment] 2023-07-28 13:06
What can we do to fix this? Yes. Review this issue, and tomorrow I'll try to have a new commit to test.

**Comment by jojo12** [comment] 2023-07-29 08:31
in 4.0.0 and 4.0.1dev:
when I say directly NO I get this error:
![grafik](https://github.com/jemproject/JEM-Project/assets/2960236/1feddd44-ff93-402e-977b-468f34e8ce4f)
because there is no entry in xxx_jem_register

**Comment by mckillo** [comment] 2023-07-30 07:16
> EDIT FROM JOJO: The first time I sas "reserved places" I thought like you. But I had a real situation with invited people and then we needed some more places for "staff" and suddenly we had a problem. So I would say: reserved places is good to have. When invited people, say: they can't come, these places will be free.

ANSWER: No, the invited user havent any reserved places or booked place, see the next image (send before in this issue).

![image](https://github.com/jemproject/JEM-Project/assets/2765316/c048776a-4638-4305-bf47-330f863cf52e)

When the invited user receives an email, the user can go to the event link and decides go or not. If there are places available, the invited user will be able to register by selecting 'yes'. If the event has 'request-answer' turned on, then the invited user can indicate that they are not going. If he says no, the invited user doesn't frees any place, it is only registered that will not go. It was like this before in JEM 2.x, but the design can be changed.

**Comment by mckillo** [comment] 2023-07-30 07:20
The tag of "Booked Places" is wrong, it's "Reserved Places" (in the image above), now upload a commit of the view.

**Comment by jojo12** [comment] 2023-07-30 07:22
I think reserved places beneath booked should be there! I don't know why, but there are always persons who don't want to register and use some other ways to attend e.g.  by phone etc. So the admin can add these people with "reserved places".

**Comment by mckillo** [comment] 2023-07-30 07:24
I agree with you, but this is a inherit. Do we change it?

**Comment by jojo12** [comment] 2023-07-30 07:30
what is a inherit? :-)

**Comment by mckillo** [comment] 2023-07-30 08:20
Sorry, write down the verb... I mean, inheritance from JEM 2.x (and EL 1.x, who knows)

**Comment by mckillo** [comment] 2023-07-30 08:24
I m not sure that I thinkn the old design of invited was right, in relation of issue #1625 (I'm sending other post to that issue to do a reflexion).

**Comment by jojo12** [comment] 2023-07-30 10:15
I don't see a problem

**Comment by mckillo** [comment] 2023-07-30 10:38
I think that the admin can invite with or without reserved place. If when the admin adds an invited user to the event, but the places filed is 0, don't reserve any place, if places field is 1 or X (other number), that user has x reserved places, but in this case, we have to return the places to 0 (see issue #1625, we change 0 (ghost) to 1 (min).

**Comment by jojo12** [comment] 2023-07-31 08:34
persists this issue as a bug?

**Comment by mckillo** [comment] 2023-07-31 15:01
No, as a bug, I think that it can be a redesign of the invited places.
I'm not sure what I'm thinking about invited places. Do you want to count it as a booked place, a reserved place, or nothing (now)?

**Comment by mckillo** [comment] 2023-07-31 16:00
In that case, can be closed.

**Closed** 2023-08-03 11:33 UTC
Labels: feature request, J4
