### ISSUE TITLE
Ambiguity in en-GB source strings leads to bad translations

### ISSUE THREAD

**Issue by jobrusche** [jemproject/JEM-Project#1755] opened 2024-05-13 09:23 UTC
In the en-GB source language strings the word "State" is used with at least 3 different meanings:

1) State = country or administrative entity within a country
2) State = status

For a translator it is sometimes difficult to determine which translations should be used. For example in the context of a venue definition it is clear what translation must be used. In other cases the context is unknown.

Names of keys like COM_JEM_SHOWSTATE and COM_JEM_STATE do not help either. It would help if the keyname said COM_JEM_STATUS

**Comment by jojo12** [comment] 2024-05-16 05:49
Hi jobrusche, it's true, but it's an very old discussion, which comes back. I think, the key "COM_JEM_STATUS" is used for the status (1) and ...STATE for state(2).
The problem is: in transifex you don't have the context which is needed to translate.
Thanks for your work!

**Comment by jojo12** [comment] 2024-05-25 08:27
the problem is: Joomla uses STATE alsways as "status". What would be the alternative in JEM for State = country or administrative entity within a country?  is there a synonym?

**Comment by ernst67** [comment] 2024-05-25 09:43
I have made a translators remark on Transifex how this string is to be interpreted

**Comment by jojo12** [comment] 2024-08-08 06:12
This is in Settings>Config Info too:
The column title in german is: "Bundesland"
to do:
change
administrator/components/com_jem/views/settings/default_configinfo.php 
line 46 to:
                    `<th><u><?php echo Text::_('JSTATUS'); ?></u></th>`

**Comment by jojo12** [comment] 2024-08-08 06:17
committed with [8a4a3da](https://github.com/jemproject/JEM-Project/commit/8a4a3da9c8063e12818d76035627fb9418f56585)

**Closed** 2024-08-25 18:25 UTC
Labels: fixed
