### ISSUE TITLE
event registration for a whole serie of events (class)?

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1764] opened 2024-06-09 10:23 UTC
if there is a serie of events, do I have to registrate for each event separately? Or can I registrate for the whole serie?
When I am registrated for the whole serie and I am absent only for one of these events?

**Comment by jojo12** [comment] 2024-06-10 07:46
From #1762:

> "There is an other mentionned problem: Is the eventregistration for the whole recurrence, or only for each event separately?
Now, the registration is for each event.
The registration process doesn't see the concurrence serie.

Good point, I have to think how to do it. I'll make a note of that.

**Comment by mckillo** [comment] 2024-06-10 08:27
![image](https://github.com/jemproject/JEM-Project/assets/2765316/478431a7-a684-47a8-b2b4-fea8c68e984c)

I'm with it. When the admin creates a new event with registration, a new option indicates if the places are for the all events of serie or not (as now, each event has its registration). I'm change the code to do it.

**Comment by mckillo** [comment] 2024-07-04 22:03
This feature is included into beta 1 of  "Review of Recurrences" branch #1762
Now, the admin can create a recurrence event and set "Series event booking", so the user can do the registration in all events of series from now until last event of the recurrence.

**Comment by jojo12** [comment] 2024-07-07 10:25
`ERROR: Registration failed! [id: 177]`
I was attending the whole serie. Then I choosed that I can't attend: I got the above mentionned error.
It continues to show me as unregistered
But it writes I am "registered", but asks me: Will you go to this event?
When I choose this, then same `ERROR: Registration failed! [id: 177]` 
but after that
it shows me as registered,
and it writes "you are registered" and I can choose to unregister. (then the circle caan begin again).

**Comment by jojo12** [comment] 2024-07-07 10:28
is this right: when I am registered in the root of the serie. When I then go e.g. to the last event of the serie and unregister, then this event is unregistered, but the rest of the serie persists as registered.??

**Comment by jojo12** [comment] 2024-07-07 11:20
todo: add in jem_mailer plugin
todo: Backend Reg.Users list: should have a column for "root event booking"
Congratulations: big progresses with this

**Comment by mckillo** [comment] 2024-07-08 07:59
Update the capture about this new option "Series event booking"

![image](https://github.com/jemproject/JEM-Project/assets/2765316/0b6184ae-54d8-48b9-9eec-ee39b4e81d19)

I am going to upload commits to fixed the issues founded.

**Comment by mckillo** [comment] 2024-07-08 08:08
I have a question about not attending a recurring event.

If the event is recurring, we should give the option to not attend a specific event in the series or unregister from the entire series from today until the end.

**Comment by jojo12** [comment] 2024-07-08 08:28
Good question!
If this is possible, it needs both: 
An attending user wants to inform, he can't participate on one session.
Or an attending user is inscripted for the whole serie, for which he can't participate.

**Comment by mckillo** [comment] 2024-07-08 09:16
Tell me if it's good this option to have both ways:
![image](https://github.com/jemproject/JEM-Project/assets/2765316/8ead713a-e840-4c6c-a7a9-5a9fcfc14daa)

**Comment by jojo12** [comment] 2024-07-08 09:36
Sorry, I don't understand!

**Comment by mckillo** [comment] 2024-07-08 10:34
@jojo12 Here you are a new commit with solutions:
Fix deprecated in eventlist view for events with dates.
Don't show date row [January 1970) for event with open dates.
Applied style to Month row (.row-month) in eveentlist view
Add strings for al month, so the Month row can be custom by languages.

**Comment by mckillo** [comment] 2024-07-08 10:35
Sorry, I mix the commit between issues 1764 y 1744, they are the same branch.

**Comment by mckillo** [comment] 2024-07-08 10:41
> Sorry, I don't understand!
If new check isn't active (by default)

We have to scenaries:
1. The user wants to unregister 1 event. 
    The user doesn't check the checkbox. In this case, the register user for this event is marked as deleted.

2. The user would like to unregister this event and the rest of the series event. 
    In this case, the user must set the checkbox. So, the register for this user is eliminated for all event active of series from now on.

I hope to explain best now. Do you agree?

**Comment by jojo12** [comment] 2024-07-08 11:46
Yes, I think I've understood and this is ok.
I have to search, how to translate this in german :-)

**Comment by mckillo** [comment] 2024-07-08 11:54
We can change the sentence of checkbox, any suggestion?

**Comment by mckillo** [comment] 2024-07-08 11:54
In the afternoon or tomorrow, I'll apply a new commit for it.

**Comment by jojo12** [comment] 2024-07-08 14:10
actual testing: 
when I book somewhere in a serie, then I am inscribed in each event of the serie. OK
when I choose unattending somewhere in the serie, then from this day on, I am unattending until to the end.
my question: if someone can't participate one day in a class, it should be possible to write unattending only for this day?

**Comment by jojo12** [comment] 2024-07-08 15:17
in the frontend view the "series event booking" would better be a check or yes or only a text, than 1. (This is not a count how many persons are booked.)
if there is no serie event booking, it would be better to hide this.

**Comment by mckillo** [comment] 2024-07-08 15:52
Answer to your question: If the user can't participate one day, this new checkbox must unset in the registration form:

![image](https://github.com/jemproject/JEM-Project/assets/2765316/f6430789-d340-468a-8a1a-9abd61a21a07)

Only for the incoming events, if the event passes, the user can't unregister for this event.
I think I'll have it finished by tomorrow.

**Comment by mckillo** [comment] 2024-07-08 15:55
When the admin edits the root event, the new option ""Series event booking" is a checkbox

![image](https://github.com/jemproject/JEM-Project/assets/2765316/730aa5d7-1356-494f-bc65-44da6a01bba3)

Where do you see a number '1'?

**Comment by mckillo** [comment] 2024-07-08 16:01
If the event hasn't set the option "Series event booking" because the admin can change the setting of this event.

In this case, if the event has set the “Registration” and there are any users with places booked, the admin has a problem because now, when the root event is saved again, broken the recurrence (series) and all events are independent. JEM works so. This issue will be a new design review (now not).

**Comment by jojo12** [comment] 2024-07-08 20:13
![20240708_221041](https://github.com/jemproject/JEM-Project/assets/2960236/5a79f18d-fc30-4d5f-894b-a9b4348af4d0)

**Comment by mckillo** [comment] 2024-07-09 06:26
I see the 1 :-) Thanks and change to hidden.

**Comment by mckillo** [comment] 2024-07-09 06:32
To not attend, we give the option to unregister from the series, but in that case, we should give the option to unregister only for the event or also for the series.

![image](https://github.com/jemproject/JEM-Project/assets/2765316/2a668ca0-2efc-43f1-90d2-f902cfa92816)

What your opinion?

If there are two options (only events, series), it may be that the admin does not want to have it, that is, he only wants to have events where users register for the series (all events), and there is no option to regsiter for an event, and in that case, we need another parameter in the setting of event where the admin indicates that (viable).

**Comment by mckillo** [comment] 2024-07-09 06:38
If the admin set “Series event booking” and unset "Enable single reservations for series”, then the checkboxes don't display in the registration form.

**Comment by jojo12** [comment] 2024-07-09 07:07
?
is the following possible? : attending and unattending for the whole serie, you must register in the root event (only, when it's a serie (When saving event registering, I've seen, it does not separate into single events).
when it's a serie and you unregister in a following event (of a serie), then it's only "unattending on this date".

**Comment by mckillo** [comment] 2024-07-09 07:43
Now, when a user books an event and this event is in a series, all events of this series are booked if the first event doesn't pass. Each event of this series is registered with the ID user in the jem_register table. Thus, if the series is broken, the user registration to the events is not broken (if the admin makes some change and saves).

If the first event and others following event are passed, and the user books an incoming event of the series, then the user is registered for all active events of this series from now on (In the pass events the user won't be registered).

Now, when the user wants to unattending an event of series, this user is unregistered from all incoming events of this series. The new checkbox (unchecked) in the registration form is to have the option of unattended one event.

If the admin wants to create a recurrence event and doesn't want to register or unregistered of individual event of this series, then I proposal you a new option with checkbox in the setting of event “Single reservations for series".  In this case, when the user wants to unattending an event, the action is for all events of the series from now on.

**Comment by mckillo** [comment] 2024-07-09 12:33
If "Single reservations for series" checkbox is unset then the user can't book single event of this series.

![image](https://github.com/jemproject/JEM-Project/assets/2765316/a2463fa3-87bc-4bd9-8080-ca8cd59e45a6)

Do you like it?

**Comment by jojo12** [comment] 2024-07-09 12:41
yes, let me try.

**Comment by mckillo** [comment] 2024-07-09 12:43
In the afternoon, I'm going to finish this new commit and I will upload it.

**Comment by mckillo** [comment] 2024-07-09 19:10
I am enhancing the options and case information; now the events of the series for which the user is registered are displayed.

![image](https://github.com/jemproject/JEM-Project/assets/2765316/12e2b06c-0406-445b-ab44-389fe4aec869)

"But now I'm going to watch the Spain-France match."

**Comment by jojo12** [comment] 2024-07-09 19:17
I can understand this, me too, I am looking. But tomorrow we go direction Austria. Means: less time.

**Comment by jojo12** [comment] 2024-07-09 20:55
Ole!!!

**Comment by mckillo** [comment] 2024-07-10 06:38
TEST SCENARIOS for beta 2:
Create a recurrence (active some repetition option until end date) event with registration active (set 'Series event booking' with or without 'Single event booking').

In the frontend, register for the event with several users and verify that the registration and non-attendance are correct. It can be verified in the backend events view (user manager).

You can also do manual registrations from the backend

If 'Series event blocking' is active, the user can enter any event in the series and by registering for that event, they are registering for all events in the series from now until the end of the series.

If "Series event blocking' is active, and "Registration annulation is Yes", then the user enters an event to mark that they are not attending, as it is an event with "Series event booking" active, the user deletes their registration in all future events of that series from now on.

"Single event booking" is a suboption of "Series event blocking" when it is active. If "Single event booking" is set, then an option appears in the end of registration form (unchecked checkbox type). By default, the user's registration is only for that event, it is not registered for the entire series. If the user wants to attend and register for all events in that series from now until the end, they must check the checkbox. The same thing happens when the user does not want to attend an event, if "Single event booking" is active, you have the option with a checkbox at the end of registration form to remove your user's registration for the events of that series shown in the table and for which you are registered (when the status is attending or waiting list).

I hope this explanation helps to understand the use and to carry out tests. I hope this explanation helps to understand the use and to carry out tests. Any help testing combinations is appreciated.

**Comment by mckillo** [comment] 2024-07-10 06:50
You can use the "Toggle Inline Help" button to have a short description about these new options.

![image](https://github.com/jemproject/JEM-Project/assets/2765316/20168802-db54-4bc9-86c2-15fc459f1c30)

**Comment by mckillo** [comment] 2024-07-11 06:42
**New idea for beta 3**

If I change the title of one recurrence event and save, why do we have to dissolve all event of recurrence? Loose the link with id, users registered ,... If the recurrence options haven't changed.

My proposal:
Be able to change the data of a recurrence event and update it, if the recurrence options are not changed. Thus, these events can be edited and modified each case, and the series is maintained. 

For example, you can have a course every friday of the week, but with a different title, content, even a different time, in a different place,... and the user can do the registration for all events of series.

Imagine if they were summer concerts, because the singer or group would be different, including the start time, description, images or location.

And the best thing, I can modify each event as many times as I need, without losing the link to the ID, nor losing the registered users. And if you want, you can send event data update emails to registered users.

But if you change any data about the recurrence of the event, then, if it is the first element, the series is dissolved as before (the events of the series are left without recurrence) and a new series of events is created again as defined. And if it is not the first element of recurrence, that event is left out of the recurrence.

![image](https://github.com/jemproject/JEM-Project/assets/2765316/0258e1be-c6c4-4b9d-8cb3-db061666caae)

**Comment by jojo12** [comment] 2024-07-11 06:54
Sound good!

**Comment by mckillo** [comment] 2024-07-11 12:26
@jojo12 Here you are. I have uploaded the commit with "New idea for beta 3". When you can, test it (only backend). Thanks.

Example: 1 event with weekly recurrence -> 3 events, and all of them have modified in hours, categories, venues and description.

![image](https://github.com/jemproject/JEM-Project/assets/2765316/ede85ec0-264c-4186-94ff-96d8072c6b59)

And the user can see the event list of series into registration form:

![image](https://github.com/jemproject/JEM-Project/assets/2765316/8a33ef5d-87c7-42de-b957-fc31160b2f69)

the user can register for this event or all events of series from now (in this case: singlebooking is active).

I think that this new feature gives more flexibility to JEM and better case of use for recurrence events.

**Comment by mckillo** [comment] 2024-07-11 15:28
On the previous screen, if the user marks the checkbox (end line), the user will see the following view for the same event:

![image](https://github.com/jemproject/JEM-Project/assets/2765316/bd8332bb-db1f-4798-927e-b0f172c2f6a2)

In this view, the user can:
- Indicate "I will NOT attend this event" (only)
- See the list of events and status in this series for which they are registered
- Mark the checkbox to indicate the user will not attend any of the events (all) and to unregister as well.

**Comment by jojo12** [comment] 2024-07-11 16:32
backend I can see, frontend no events,

**Comment by mckillo** [comment] 2024-07-11 17:00
I think that you haven't applied \administrator\components\com_jem\sql\updates\mysql\4.2.3.sql
Run at less this line in your mysql:

`ALTER TABLE `#__jem_events` ADD `singlebooking` INT(1) NOT NULL DEFAULT '0' AFTER `requestanswer`;`

Remember to change #_ for your Joomla prefix.

**Comment by mckillo** [comment] 2024-07-11 17:08
I have update the commit with small fix (some details about style, order).

**Comment by jojo12** [comment] 2024-07-12 13:05
I made a package from jem_4.2.3_dev and installed on a fresh.
But strange: I can't create a new event, I can't choose a category (I created), but it refuses to choose it!

**Comment by jojo12** [comment] 2024-07-12 13:06
with what shall I test now?

**Comment by mckillo** [comment] 2024-07-12 14:02
Send me that zip, I don't find it in the root of branch 4.2.3

**Comment by Heklaterriol** [comment] 2024-07-12 15:06
I can reproduce it.
I created a package from the state of the art, which causese an error:
https://github.com/jemproject/JEM-Project/blob/JEM-4.2.3-dev/pkg_jem_error_build_20240711-v1.zip

**Comment by mckillo** [comment] 2024-07-12 18:41
Sorry, I uploaded the $save variable force in my recurring event tests and didn't upload the right line for the final version. Fixed (see commit)

**Comment by Heklaterriol** [comment] 2024-07-12 19:50
Thank you, @mckillo
I created an new nightly, which seems to work now.
https://github.com/jemproject/JEM-Project/blob/JEM-4.2.3-dev/pkg_jem_nightly_build_20240712-v1.zip

**Comment by jojo12** [comment] 2024-07-12 20:33
installed, fine
open attendees manager in frontend:
error
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.published, a.created, a.created_by, a.created_by_alias, a.locid, a.registra,...' at line 1

**Comment by jojo12** [comment] 2024-07-12 20:44
is this right, even when eventtitel is changed, the alias persists the same?

**Comment by mckillo** [comment] 2024-07-13 07:19
> is this right, even when eventtitel is changed, the alias persists the same?

Yes, if you edit an event and change de title, the alias does not change, the same as in Joomla. 
The admin can change manually the alias field.

**Comment by mckillo** [comment] 2024-07-13 07:52
@jojo12 Now, the admin can edit a recurrence event from backend, change the title and alias, but if delete the alias field then when the event is saved, the alias is generated automatically. 
If this same event is edited from FE, the admin can't change the alias, if the title is changed, the alias doesn't change like Joomla.

An event edited is updated when it only is recurrence type (uploaded last commit)

**Comment by mckillo** [comment] 2024-07-17 11:49
New feature: Create a new recurrence event from child of a series.
If the recurrence setting is modified in a child event then this event is converting to root as a new recurrence event and all events of this new recurrence are created.

**Comment by jojo12** [comment] 2024-07-19 08:48
I would say, to be more clear, we have to give an other order, e.g.
![grafik](https://github.com/user-attachments/assets/20d20b00-a1cc-4298-9437-2e339fc0955e)

**Comment by jojo12** [comment] 2024-07-19 09:21
I don't understand:
![grafik](https://github.com/user-attachments/assets/8af2c1d4-3e25-4657-86ad-a5e3c2c0dff3)

**Comment by jojo12** [comment] 2024-07-19 13:12
I think, it should be written in the table of the printscreen registration status: "Not attending" ?

**Comment by jojo12** [comment] 2024-07-19 13:15
When I change something it writes: contactid and the id of the event. But I think contactid is something else?

**Comment by mckillo** [comment] 2024-07-19 15:33
Let's take it step by step.

The table change its position.

 ![image](https://github.com/user-attachments/assets/4409c4bb-72e8-4d96-867b-ee2d9052e8dd)
 
 Better?

**Comment by mckillo** [comment] 2024-07-19 16:24
The option is "I will NOT go to this event" is showing because you have marked “Request answer” or before the user has some registered for this event.

**Comment by mckillo** [comment] 2024-07-19 18:03
@jojo12 Test it again.

In the first moment, the user sees this registration form for the recurrence event.

![image](https://github.com/user-attachments/assets/4aa60479-4cc3-4b00-ab75-00ffc10f41f8)

**Comment by jojo12** [comment] 2024-07-19 19:46
I will continue with testing tomorrow.
How is it possible to register for the whole series of events. And then to unregister the second or third event.
to unregister only the first event, works well. But the other following events, it says "you can't unregister".

**Comment by jojo12** [comment] 2024-07-19 19:48
In the list of events of a series, the actual event is not listed. (I think it would be better, to list the integral group of events.

**Comment by mckillo** [comment] 2024-07-20 06:48
If the actual event is not listed, then this event has already started.

If the singlebooking is off and seriesbooking is on, you must unregister from any event.

If the singlebooking is off and seriesbooking is off, you only can unregister in this event.

If the singlebooking is on and seriesbooking is on, you can choose to unregister for this event or all events of series from now on where you are registered.

If the singlebooking is on and seriesbooking is off, this setting doesn't work, singlebooking needs that seriesbooking is on to work.

It doesn't work, then I need to know your setting (event, recurrence, repetition), so I can try to simulate the issue.

**Comment by mckillo** [comment] 2024-07-20 06:55
Be careful with the hours, they are also compared. 
Events from now on are:` If enddates>dates or if endates=dates and times>now`
If you have an event open today (without a start time), it is understood that it has started. 
If the event is today at 10:00 and it is 10:00, the event has started.
And therefore, these events are not shown in the events table to be recorded.

**Comment by jojo12** [comment] 2024-07-20 14:37
Meanwhile I  understand much more :). Because of that I deleted wrong question with answers.
For new problems I made new issues.

**Closed** 2024-07-22 12:25 UTC
Labels: enhancement, fixed

**Comment by pctech-switzerland** [comment] 2024-08-21 05:42
Hi JEM team, where im able to Download for Testing?
best Regards, Marcel

**Comment by mckillo** [comment] 2024-08-21 10:12
In the root of JEM-4.2.3-dev branch, last zIp is: https://github.com/jemproject/JEM-Project/blob/JEM-4.2.3-dev/pkg_jem_nightly_build_20240820-v1.zip
