### ISSUE TITLE
in backend/attachments icon wrong and should have a tooltip

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#882] opened 2015-01-30 09:39 UTC
in JEM 2.1.1 I had two attachments for an event. I looked in backend, then I saw on the right side (see image) a red icon (there was no tooltip) so I thought, the attachment is not yet published. And clicked it. Then the attachment was deleted.

in 3.0.6 there's is an other icon and after all there is a tooltip when hoovering over, which makes it clear.

in 2.1.1 this should be changed.

**Comment by Hoffi1** [comment] 2015-01-30 10:36
Hm... because the old layout was unusable on J! 3 (caused by the side menu which limit the width) I used nearly the same code as in frontend.
But I agree a tooltip will be very helpful to prevent mistakes.

**Comment by jojo12** [comment] 2015-01-30 10:53
i am not sure about the icon too: is this an official one for delete?
bluefox uses a white x on red, which seems more clear for me. 
(But it's after all the tooltip)

**Comment by JKoelman** [comment] 2015-01-30 11:01
am using publish_r.png and the one here is publish_x.png

**Comment by Hoffi1** [comment] 2015-01-30 12:02
Scheint so, mit Joomla! 3 will man uns ein X für ein R vormachen - sorry, there is no matching translation with x and u :wink: What I mean: I think in J! 2.5 publish_x was a white x on red bubble, which should be ok for Delete. The second icon is a white dot on red bubble which is used for Unpublished. So I have to check if there is a dot or x.
I think we use our own icon (which was copied from Joomla) because they are template dependent. Maybe there is something mixed up.
But the tooltip will be implemented, guaranteed!

**Comment by Hoffi1** [comment] 2015-01-30 12:22
Ok, looked into code. On frontend publish_r.png (white x) is used where on backend it's publish_x.png (white dot). So this has to be changed.
Also the title param is missing so no tooltip is shown on backend.

Thanks for your detection, @jojo12. Will be fixed today evening.

**Comment by jojo12** [comment] 2015-01-30 12:44
working together, as good as we can!

**Closed** 2015-02-15 23:26 UTC
Labels: bug, fixed
