### ISSUE TITLE
Error when Indexing for Smart Search/Finder 

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1605] opened 2023-07-06 11:31 UTC
We already had this error before (I couldn't finde the issue)

On a clean JEM 4.0.0 installation when trying to index for Smart Search I get the following message (and no events are indexed):

```
An Error Has Occurred

The following message was returned by the server:
A parse error has occurred while processing the following JSON data:
JSON.parse: unexpected character at line 1 column 1 of the JSON data

JEM    0 of 6
Categories    0 of 5
Contacts    0 of 1
Content    0 of 1
Newsfeeds    0 of 0
Tags    0 of 0
```

With _JEM - Smart Search Plugin_ disabled I don't get any errors

in the error log I didn't find any useful information, just:
```
#Fields: datetime	priority clientip	category	message
2023-07-06T11:23:09+00:00	INFO 93.224.xx.xx	-	Starting the indexer
2023-07-06T11:23:09+00:00	INFO 93.224.xx.xx	-	Starting the indexer batch process
2023-07-06T11:23:09+00:00	INFO 93.224.xx.xx	-	Batch completed, peak memory usage: 29,360,128 bytes
```

**Comment by mckillo** [comment] 2023-07-07 06:50
I have tried to simulate the error, but I didn't find it. Tell me any more details to see it (capture, envioroment, action, views).

**Comment by Heklaterriol** [comment] 2023-07-08 19:28
I don't have much more information, see the screen capture. It is once with the JEM Smart Search plugin enabled (indexing error), once with the plugin disabled (index works fine)

https://github.com/jemproject/JEM-Project/assets/28540581/4e6e76e7-142f-48eb-93b5-97527694a25b

**Comment by Heklaterriol** [comment] 2023-08-29 07:37
I would like to get this problem solves and did some research.

**Issue**: JEM events and categories are not indexed

With Error reporting off there is no error 
With Error reporting on maximum I get 

An Error Has Occurred
The following message was returned by the server:
A parse error has occurred while processing the following JSON data:
JSON.parse: unexpected character at line 1 column 1 of the JSON data
![jemsmartsearcherror](https://github.com/jemproject/JEM-Project/assets/28540581/1d5ebd6e-acc3-4a3f-a326-3566a1921b5c)

I found out that I can use the CLI (Command Line Interface) to geht more information:

With the command `php cli/joomla.php -v finder:index` I get the following output:
```
 Starting Indexer
 Setting up Smart Search plugins

Setup 15 items in 0.012 seconds.

In route.php line 229:
                                                                                 
[Error]                                                                        
Call to undefined method Joomla\CMS\Application\ConsoleApplication::getMenu()                                                                                   

Exception trace:
 
at /www/htdocs/w01374a6/subdomain-access/jem4dev.datenablage.info/components/com_jem/helpers/route.php:229

JEMHelperRoute::_findItem()
at /www/htdocs/w01374a6/subdomain-access/jem4dev.datenablage.info/components/com_jem/helpers/route.php:131

JEMHelperRoute::getEventRoute()
at /www/htdocs/w01374a6/subdomain-access/jem4dev.datenablage.info/plugins/finder/jem/jem.php:282

plgFinderJEM->index()
at /www/htdocs/w01374a6/subdomain-access/jem4dev.datenablage.info/administrator/components/com_finder/src/Indexer/Adapter.php:244

Joomla\Component\Finder\Administrator\Indexer\Adapter->onBuildIndex()
at /www/htdocs/w01374a6/subdomain-access/jem4dev.datenablage.info/libraries/src/Plugin/CMSPlugin.php:284

Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}()
at /www/htdocs/w01374a6/subdomain-access/jem4dev.datenablage.info/libraries/vendor/joomla/event/src/Dispatcher.php:486

Joomla\Event\Dispatcher->dispatch()
at /www/htdocs/w01374a6/subdomain-access/jem4dev.datenablage.info/libraries/src/Application/EventAware.php:111

Joomla\CMS\Application\ConsoleApplication->triggerEvent()
at /www/htdocs/w01374a6/subdomain-access/jem4dev.datenablage.info/libraries/src/Console/FinderIndexCommand.php:388

Joomla\CMS\Console\FinderIndexCommand->index()
at /www/htdocs/w01374a6/subdomain-access/jem4dev.datenablage.info/libraries/src/Console/FinderIndexCommand.php:209

Joomla\CMS\Console\FinderIndexCommand->doExecute()
at /www/htdocs/w01374a6/subdomain-access/jem4dev.datenablage.info/libraries/vendor/joomla/console/src/Command/AbstractCommand.php:235

Joomla\Console\Command\AbstractCommand->execute()
at /www/htdocs/w01374a6/subdomain-access/jem4dev.datenablage.info/libraries/vendor/joomla/console/src/Application.php:1181

Joomla\Console\Application->runCommand()
at /www/htdocs/w01374a6/subdomain-access/jem4dev.datenablage.info/libraries/vendor/joomla/console/src/Application.php:403

Joomla\Console\Application->doExecute()
at /www/htdocs/w01374a6/subdomain-access/jem4dev.datenablage.info/libraries/src/Application/ConsoleApplication.php:206

Joomla\CMS\Application\ConsoleApplication->doExecute()
at /www/htdocs/w01374a6/subdomain-access/jem4dev.datenablage.info/libraries/vendor/joomla/console/src/Application.php:448

Joomla\Console\Application->execute()
at /www/htdocs/w01374a6/subdomain-access/jem4dev.datenablage.info/libraries/src/Application/ConsoleApplication.php:259

Joomla\CMS\Application\ConsoleApplication->execute()
at /www/htdocs/w01374a6/subdomain-access/jem4dev.datenablage.info/cli/joomla.php:76
```

I tried with my basic coder knowlegde to find the error – no success!

@mckillo Do you see anything?

**Comment by jojo12** [comment] 2023-08-29 15:18
https://docs.joomla.org/Creating_a_Smart_Search_plug-in

**Comment by jojo12** [comment] 2023-08-29 19:12
When I put the jem-finder plugin at the end of the finder plugins, then the indexer work and gives at the end the error. All the other finder plugins gave results!

**Comment by Heklaterriol** [comment] 2023-08-29 20:24
> https://docs.joomla.org/Creating_a_Smart_Search_plug-in

Yes, Inknow the document, but I lack the programming knowledge and expertise to make anything out of it.

**Comment by Heklaterriol** [comment] 2023-08-29 20:30
I also saw that the other finder plugins have a indentical files structure, different from the JEM finder plugin.

![finderplugins](https://github.com/jemproject/JEM-Project/assets/28540581/23cea3d8-329d-4045-9f98-7d45a4b9bdc1)

I copied one of them and tried to modify it for JEM, but it didn't work.

**Comment by mckillo** [comment] 2023-08-30 03:36
@Heklaterriol Received request. This weekend, I'll study this case and I 'll try to debug it (first simulation, second resolving).
Sorry, I have returned this week of my vacations and I'm full in my work.

**Comment by Heklaterriol** [comment] 2023-08-31 17:31
Yes, not hurry. It's just that you are the only real coder here :-)

**Comment by mckillo** [comment] 2023-08-31 18:03
Thanks, but I'm not a pure coder, I'm a resolving problem engineer and parts of solutions are with code ;-) I like to debug error and give solution.

I have note to try it this weekend.

**Comment by Heklaterriol** [comment] 2023-11-23 22:41
Coda friend of mine said, that he will have a look at it.

**Comment by jojo12** [comment] 2024-05-26 15:18
@mckillo;
When I look into different finder plugins (I am testing with and without compat plugin), most of the finder plugins work without the new system!
Perhaps this can help to bring to function the jem plugin:
phoca has a lot of different working finder plugins:
phocadownload, phocadownloadcategory, phocagallerycategory, phocagalleryimage, phocacartproduct.
so there are finder plugins for different extensions. We can compare them to find, what jem needs.

**Comment by Heklaterriol** [comment] 2024-05-26 15:49
I discussed this with my coder friend and he said, that JEM does not follow the recent Joomla code architecture and that's why it is difficult to just adapt an other finder plugin.

Since I'm not a programmer, I can't estimate to what extent this assessment is really correct.

**Comment by jojo12** [comment] 2024-05-26 16:14
For sure you can't use Joomla code, but other outside extension are interesting! 

For me it seems interesting too, that phoca uses different finder plugins for different things  (would say in our JEM: a plugin for events an other for venues!

**Comment by jojo12** [comment] 2024-05-27 15:11
I was comparing the different finder plugins. And suddenly I saw that jem was indexed. But it was too late, I just loosed this working file. But now I know, there must be a possibility to adapt it. (@hekla: So for me the info your dev gave, is much too easy. Sorry when I say that.)

**Comment by Heklaterriol** [comment] 2024-05-27 17:48
Cool, very nice!
Can you please make a branch for that, so I can test it too.

(My dev friend was much more complicated, not easy - he may be too perfetionistic. He would have loved to rebuild the whole architecture and code Joomla 5 conform, if he had time.)

**Comment by jojo12** [comment] 2024-05-27 18:02
sorry, but I am not a dev and I am a bit stupid.  I don't understand the whole thing, so I tried with comparing the different finder plugins (after all from outside extensions).
And I did see that some change worked, I saw it too late. So I have nothing in my hands. I will retry to finde, but because I am not a dev.
But this is important: Finder plugins in J!5 must not yet have the new structure. It's easier to update the old. (I am even testing without compatibility plugin.

**Comment by jojo12** [comment] 2024-05-30 11:46
It suddenly happened again, that I got a Index without noticing it. So in the branch jem-finder-plugin-jojo it put the jem.php I was working around, but it gives me errors, but it must be near! Please help, test and try!
(I was comparing jem-finder with different phoca finder plugins.)

**Comment by jojo12** [comment] 2024-05-31 07:39
(it seems, there must be something which is searching for state. This causes a problem in JEM with saving)

**Comment by Pinkeltje** [comment] 2024-10-12 09:48
Tried to debug with new folder structure, but no luck. However, managed to get existing smart search plugin working by changing it.  Tested only with Joomla 5.1.4 and Jem 4.2.2.
[plg_finder_jem.zip](https://github.com/user-attachments/files/17349567/plg_finder_jem.zip)
I noticed that a lot of extensions still use this folder structure for their smart search plugins.

**Comment by mckillo** [comment] 2024-10-12 16:19
Tested, and works

![image](https://github.com/user-attachments/assets/02ef7f81-09e7-458c-98a4-4c39d800954b)

Now, I load a commit with it.

Thanks.

**Comment by mckillo** [comment] 2024-10-14 03:09
![image](https://github.com/user-attachments/assets/6cbf1689-301e-4350-b50c-02b0f7d14d11)

**Comment by Heklaterriol** [comment] 2024-10-14 12:59
I still do not have JEM content in the search results…
What I have done:
- made a clean Joomla 5 installation
- clean installed JEM 4.2.2.
- update JEM to 4.3.0.rc9 (the latest package with the smart search commit)
- loaded sample JEM data and sample Joomla article data
- activated the JEM smart Search Plugin
- indexed the content and checkt it: JEM content was indexed
- made smart search with "Balkan Beatz" or "lorem ipusm" - **no results from JEM**, only from Joomla articles

What am I missing?

**Comment by Pinkeltje** [comment] 2024-10-14 13:27
For me it's working perfectly now thanks to the changes @mckillo made. 
I just updated plugin code in my existing J 5.1.4 site with JEM 4.2.2. 
Deleted all indexes en re-indexed.
Only change I made was to disable line 269
        // Get the menu title if it exists.
//        $title = $this->getItemMenuTitle($item->url);
As the index debugger threw an error.

**Comment by Heklaterriol** [comment] 2024-10-14 18:19
Yes thank you. I came across the same insight, when checking the indexing debugger.
With this line outcommented it works. Thank you!

**Comment by jojo12** [comment] 2024-10-16 14:51
now J!5.2 is official out as stable:
I get:
 Inhaltstyp
Inhaltsgruppe
Warning: Undefined array key 4 in /home/folktanz/public_html/administrator/components/com_finder/src/Field/ContentmapField.php on line 109

Warning: foreach() argument must be of type array|object, null given in /home/folktanz/public_html/administrator/components/com_finder/src/Field/ContentmapField.php on line 109

Warning: Undefined array key 11 in /home/folktanz/public_html/administrator/components/com_finder/src/Field/ContentmapField.php on line 109

Warning: foreach() argument must be of type array|object, null given in /home/folktanz/public_html/administrator/components/com_finder/src/Field/ContentmapField.php on line 109

Warning: Undefined array key 6 in /home/folktanz/public_html/administrator/components/com_finder/src/Field/ContentmapField.php on line 109

Warning: foreach() argument must be of type array|object, null given in /home/folktanz/public_html/administrator/components/com_finder/src/Field/ContentmapField.php on line 109

Warning: Undefined array key 2 in /home/folktanz/public_html/administrator/components/com_finder/src/Field/ContentmapField.php on line 109

Warning: foreach() argument must be of type array|object, null given in /home/folktanz/public_html/administrator/components/com_finder/src/Field/ContentmapField.php on line 109

Warning: Undefined array key 62 in /home/folktanz/public_html/administrator/components/com_finder/src/Field/ContentmapField.php on line 109

Warning: foreach() argument must be of type array|object, null given in /home/folktanz/public_html/administrator/components/com_finder/src/Field/ContentmapField.php on line 109

**Comment by Pinkeltje** [comment] 2024-10-16 15:25
Like I said before: unable to reproduce. Updated my local testsite yesterday to 5.2.0 RC4 - no problems, updated live site few minutes ago to J 5.2.0 stable, no problems either.

**Comment by Heklaterriol** [comment] 2024-10-16 15:26
what do you do to get these warnings (_warnings_ not errors!).
And are they definitely related to JEM?
I usually get quite some warning messages just from Joomla (without JEM)

**Comment by Heklaterriol** [comment] 2024-10-16 15:45
Thank you for your eagle eye. Nothing to be sorry for.

**Comment by Heklaterriol** [comment] 2024-10-16 16:18
in my opinion, we can cloase this issues at least for now.
Thank you Pinkeltje for your contribution!

**Closed** 2024-10-20 16:13 UTC
Labels: fixed, J5

**Comment by mckillo** [comment] 2024-10-23 10:02
Are we sure we want to activate the Finder plugin by default? 
I believe that users should be the ones to enable this plugin. I
We don't know the use and status of serach in the web of users, if Smart Search in Joomla is active or how the website is designed, especially if there isn't a search module or menu active

**Comment by mckillo** [comment] 2024-10-23 10:03
it's the same case of mailer plugin
