### ISSUE TITLE
module-basic: change code of default.php

### ISSUE THREAD

**Issue by JKoelman** [jemproject/JEM-Project#958] opened 2015-07-09 18:47 UTC
the code in default.php should be changed a little to have a div and the ul/endif should be a bit different.

**Comment by Hoffi1** [comment] 2015-10-18 19:06
@JKoelman: It seems to be fixed, isn't it?

**Comment by JKoelman** [comment] 2015-10-18 19:09
@Hoffi1 think it is but it should be checked to be sure. Am not having JEM installed at the moment but can check later in the week

**Comment by Hoffi1** [comment] 2015-10-18 19:43
Ok, thanks. The if/ul swap is clear but the cause for the div I don't know.
I plan to prepare 2.1.5 RC1 next days where this will be part of. But I see here no cause for panic. :wink: It's more for the Changelog...

**Closed** 2015-11-04 08:05 UTC
Labels: enhancement
