### ISSUE TITLE
pagination-problem in eventslist

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#877] opened 2015-01-20 08:57 UTC
I went to the second page in eventslist, then I wanted to go back to the first page -> no chance.

**Comment by jojo12** [comment] 2015-01-20 08:59
I know, it's an old problem, but I thought, it was fixed

**Comment by Hoffi1** [comment] 2015-01-20 10:40
It's a duplicate of #841.
It is fixed here on GitHub but will be contained in JEM 2.1.2. (generally it's a problem of Joomla but I decided to let JEM tolerate this problem)

**Closed by Hoffi1** 2015-01-20 10:40 UTC
Labels: duplicate
